### ISSUE TITLE
uwsgi 2.0.14 can not compile with pypy5.7

### ISSUE THREAD

**Issue by toplinuxsir** [unbit/uwsgi#1499]
uwsgi 2.0.14 can not compile with pypy5.7, erros as below:
 [thread 0][gcc -pthread] plugins/pypy/pypy_plugin.o
    core/ssl.c: In function ‘uwsgi_ssl_init’:
    core/ssl.c:17:9: warning: ‘OPENSSL_config’ is deprecated [-Wdeprecated-declarations]
             OPENSSL_config(NULL);
             ^~~~~~~~~~~~~~
    In file included from /usr/include/openssl/crypto.h:32:0,
                     from /usr/include/openssl/bio.h:20,
                     from /usr/include/openssl/conf.h:13,
                     from ./uwsgi.h:356,
                     from core/ssl.c:1:
    /usr/include/openssl/conf.h:92:1: note: declared here
     DEPRECATEDIN_1_1_0(void OPENSSL_config(const char *config_name))
     ^
    core/ssl.c: In function ‘uwsgi_ssl_info_cb’:
    core/ssl.c:26:24: error: dereferencing pointer to incomplete type ‘SSL {aka const struct ssl_st}’
                     if (ssl->s3) {
                            ^~
    core/ssl.c: In function ‘uwsgi_ssl_session_new_cb’:
    core/ssl.c:62:69: error: dereferencing pointer to incomplete type ‘SSL_SESSION {aka struct ssl_session_st}’
             if (uwsgi_cache_set2(uwsgi.ssl_sessions_cache, (char *) sess->session_id, sess->session_id_length, session_blob, len, uwsgi.ssl_sessions_timeout, 0)) {
                                                                         ^~
    core/ssl.c: In function ‘uwsgi_ssl_new_server_context’:
    core/ssl.c:408:46: warning: passing argument 2 of ‘SSL_CTX_sess_set_get_cb’ from incompatible pointer type [-Wincompatible-pointer-types]
                     SSL_CTX_sess_set_get_cb(ctx, uwsgi_ssl_session_get_cb);
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~
    In file included from ./uwsgi.h:357:0,
                     from core/ssl.c:1:
    /usr/include/openssl/ssl.h:621:6: note: expected ‘SSL_SESSION * (*)(struct ssl_st *, const unsigned char *, int,  int *) {aka struct ssl_session_st * (*)(struct ssl_st *, const unsigned char *, int,  int *)}’ but argument is of type ‘SSL_SESSION * (*)(SSL *, unsigned char *, int,  int *) {aka struct ssl_session_st * (*)(struct ssl_st *, unsigned char *, int,  int *)}’
     void SSL_CTX_sess_set_get_cb(SSL_CTX *ctx,
          ^~~~~~~~~~~~~~~~~~~~~~~
    core/legion.c: In function ‘uwsgi_legion_register’:
    core/legion.c:1077:44: error: invalid application of ‘sizeof’ to incomplete type ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
      EVP_CIPHER_CTX *ctx = uwsgi_malloc(sizeof(EVP_CIPHER_CTX));
                                                ^~~~~~~~~~~~~~
    core/legion.c:1112:45: error: invalid application of ‘sizeof’ to incomplete type ‘EVP_CIPHER_CTX {aka struct evp_cipher_ctx_st}’
      EVP_CIPHER_CTX *ctx2 = uwsgi_malloc(sizeof(EVP_CIPHER_CTX));
                                                 ^~~~~~~~~~~~~~

**Comment by xrmx** [comment]
@toplinuxsir  these are openssl 1.1 warnings, please try uwsgi-2.0 branch

**Comment by toplinuxsir** [comment]
@xrmx Yes, It works ! Thanks
