### ISSUE TITLE
mod_proxy_uwsgi fails to compile in Apache 2.4

### ISSUE THREAD

**Issue by bgibson710** [unbit/uwsgi#197]
When I attempt to run apxs -I -c mod_proxy_uwsgi.c in an Apache 2.4 environment I get the following output:

mod_proxy_uwsgi.c: In function uwsgi_response:
mod_proxy_uwsgi.c:289:2: warning: implicit declaration of function ap_proxy_make_fake_req [-Wimplicit-function-declaration]
mod_proxy_uwsgi.c:289:20: warning: initialization makes pointer from integer without a cast [enabled by default]
mod_proxy_uwsgi.c: In function uwsgi_handler:
mod_proxy_uwsgi.c:412:33: error: proxy_worker has no member named name
apxs:Error: Command failed with rc=65536
