### ISSUE TITLE
uwsgi 2.0.9 compile error and segfault issue with psgi plugin

### ISSUE THREAD

**Issue by raigad** [unbit/uwsgi#865]
Hi, 

First of all uwsgi-2.0.9  does not compile psgi plugin I get following message. 
```
*** rack plugin built and available in rack_plugin.so ***
*** building plugin: psgi ***
[gcc -pthread] psgi_plugin.so
cc1: warnings being treated as errors
plugins/psgi/psgi_loader.c: In function 'xs_init':
plugins/psgi/psgi_loader.c:305: error: value computed is not used
plugins/psgi/psgi_loader.c:310: error: value computed is not used
plugins/psgi/psgi_loader.c:313: error: value computed is not used
*** unable to build psgi plugin ***
```
So I had to remove cflags **-Werror** from uwsgiconfig.py  to get  it compiled. 

```
diff -Naur uwsgi-2.0.9/uwsgiconfig.py uwsgi-2.0.9_new/uwsgiconfig.py
--- uwsgi-2.0.9/uwsgiconfig.py  2014-12-29 09:07:07.000000000 +0000
+++ uwsgi-2.0.9_new/uwsgiconfig.py  2015-03-03 17:15:05.044439270 +0000
@@ -630,7 +630,7 @@
             self.include_path += os.environ['UWSGI_INCLUDES'].split(',')


-        self.cflags = ['-O2', '-I.', '-Wall', '-Werror', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64'] + os.environ.get("CFLAGS", "").split() + self.get('cflags','').split()
+        self.cflags = ['-O2', '-I.', '-Wall', '-D_LARGEFILE_SOURCE', '-D_FILE_OFFSET_BITS=64'] + os.environ.get("CFLAGS", "").split() + self.get('cflags','').split()

         report['kernel'] = uwsgi_os

```

and second issue is that when uwsgi 2.0.9 is installed it sets master flag true by default but if you try to set value of master flag to true or false it I get Segmentation fault.  May be it has to to with init script not parsing params correctly. 
Note: that this is working fine with uwsgi-2.0.8

```
*** Operational MODE: preforking ***
!!! uWSGI process 120774 got Segmentation Fault !!!
*** backtrace of 120774 ***
/usr/sbin/uwsgi(uwsgi_backtrace+0x29) [0x467a39]
/usr/sbin/uwsgi(uwsgi_segfault+0x21) [0x467bc1]
/lib64/libc.so.6() [0x3fd20326a0]
/usr/lib64/uwsgi/psgi_plugin.so(xs_init+0x51b) [0x7f1516fd3f2b]
/usr/lib64/perl5/CORE/libperl.so() [0x3f3c24a975]
/usr/lib64/perl5/CORE/libperl.so(perl_parse+0x493) [0x3f3c24d643]
/usr/lib64/uwsgi/psgi_plugin.so(init_psgi_app+0x1b3) [0x7f1516fd28d3]
/usr/sbin/uwsgi(uwsgi_init_all_apps+0xa2) [0x465482]
/usr/sbin/uwsgi(uwsgi_start+0xe2a) [0x466e7a]
/usr/sbin/uwsgi(uwsgi_setup+0x17c7) [0x46b0a7]
/usr/sbin/uwsgi(main+0x9) [0x46bf99]
/lib64/libc.so.6(__libc_start_main+0xfd) [0x3fd201ed5d]
/usr/sbin/uwsgi() [0x418bc9]
*** end of backtrace ***

```

Regards
Rohit

**Comment by unbit** [comment]
The lreturn value has been fixed some week ago in stable branch, regarding the segfault i fear it is generated by some build procedure error. Can you report your build profile (or make a psgi only build just for testing) ?

**Comment by xrmx** [comment]
No user response since months, compilation error already fixed. Closing.
