### ISSUE TITLE
uwsgi fails to compile with Python 3.13 

### ISSUE THREAD

**Issue by gmc444-b** [unbit/uwsgi#2651]
When attempting to install uWSGI with Python 3.13, I get compiler errors like the following:
```
  plugins/python/uwsgi_python.h:178:9: error: unknown type name '_PyCFrame'
     178 |         _PyCFrame **current_frame;
            |         ^~~~~~~~~
```

With 3.13, the _PyCFrame struct was removed, as documented in the [changelog](https://docs.python.org/3.13/whatsnew/changelog.html#changelog) and in [gh-108035](https://github.com/python/cpython/issues/108035).

Looking at the source, it appears that [this line](https://github.com/unbit/uwsgi/blob/master/plugins/python/uwsgi_python.h#L24) is defining UWSGI_PY312, which in turn takes the wrong option in an if statement further down (line 189) and the code would probably work if it took the else clause at line 203.

**Comment by xavierba** [comment]
#2655 should fix this.

**Comment by xrmx** [comment]
This will be fixed in 2.0.27
