### ISSUE TITLE
PHP plugin build failed under FreeBSD 10

### ISSUE THREAD

**Issue by iron-udjin** [unbit/uwsgi#654]
Hello,

I tried to build uwsgi-2.0.5.1 under 10.0-STABLE r267563 use Clang 3.4.1 and got:

<pre>
[thread 1][ccplugins/php/php_plugin.c:82:6: error: use of undeclared identifier 'tsrm_ls'
        if (SG(request_info).no_headers == 1) {
            ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:86:58: error: use of undeclared identifier 'tsrm_ls'
        struct wsgi_request *wsgi_req = (struct wsgi_request *) SG(server_context);
                                                                ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:88:7: error: use of undeclared identifier 'tsrm_ls'
        if (!SG(sapi_headers).http_status_line) {
             ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:90:13: error: use of undeclared identifier 'tsrm_ls'
                int hrc = SG(sapi_headers).http_response_code;
                          ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:97:14: error: use of undeclared identifier 'tsrm_ls'
                char *sl = SG(sapi_headers).http_status_line;
                           ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:138:58: error: use of undeclared identifier 'tsrm_ls'
        struct wsgi_request *wsgi_req = (struct wsgi_request *) SG(server_context);
                                                                ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:535:2: error: incompatible pointer types initializing 'int (*)(sapi_headers_struct *, void ***)' with an expression of type 'int (sapi_headers_struct *)' [-Werror,-Wincompatible-pointer-types]
        sapi_uwsgi_send_headers,
        ^~~~~~~~~~~~~~~~~~~~~~~
plugins/php/php_plugin.c:538:2: error: incompatible pointer types initializing 'char *(*)(void ***)' with an expression of type 'char *(void)' [-Werror,-Wincompatible-pointer-types]
        sapi_uwsgi_read_cookies,
        ^~~~~~~~~~~~~~~~~~~~~~~
plugins/php/php_plugin.c:541:2: error: incompatible pointer types initializing 'void (*)(char *, void ***)' with an expression of type 'void (char *)' [-Werror,-Wincompatible-pointer-types]
        sapi_uwsgi_log_message,                                                                 /* Log message */
        ^~~~~~~~~~~~~~~~~~~~~~
plugins/php/php_plugin.c:654:2: error: use of undeclared identifier 'tsrm_ls'
        SG(server_context) = (void *) wsgi_req;
        ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:869:2: error: use of undeclared identifier 'tsrm_ls'
        SG(request_info).request_uri = estrndup(wsgi_req->uri, wsgi_req->uri_len);
        ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:870:9: error: use of undeclared identifier 'tsrm_ls'
        SG(request_info).request_method = estrndup(wsgi_req->method, wsgi_req->method_len);
        ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:871:2: error: use of undeclared identifier 'tsrm_ls'
        SG(request_info).proto_num = 1001;
        ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:873:2: error: use of undeclared identifier 'tsrm_ls'
        SG(request_info).query_string = estrndup(wsgi_req->query_string, wsgi_req->query_string_len);
        ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:874:9: error: use of undeclared identifier 'tsrm_ls'
        SG(request_info).content_length = wsgi_req->post_cl;
        ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:875:2: error: use of undeclared identifier 'tsrm_ls'
        SG(request_info).content_type = estrndup(wsgi_req->content_type, wsgi_req->content_type_len);
        ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:878:2: error: use of undeclared identifier 'tsrm_ls'
        SG(sapi_headers).http_response_code = 200;      
        ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:880:2: error: use of undeclared identifier 'tsrm_ls'
        SG(request_info).path_translated = wsgi_req->file;
        ^
/usr/local/include/php/main/SAPI.h:141:16: note: expanded from macro 'SG'
# define SG(v) TSRMG(sapi_globals_id, sapi_globals_struct *, v)
               ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:164:57: note: expanded from macro 'TSRMG'
#define TSRMG(id, type, element)        (((type) (*((void ***) tsrm_ls))[TSRM_UNSHUFFLE_RSRC_ID(id)])->element)
                                                               ^
plugins/php/php_plugin.c:887:33: error: use of undeclared identifier 'tsrm_ls'
        if (php_request_startup(TSRMLS_C) == FAILURE) {
                                ^
/usr/local/include/php/Zend/../TSRM/TSRM.h:167:18: note: expanded from macro 'TSRMLS_C'
#define TSRMLS_C        tsrm_ls
                        ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
*** [all] Error code 1

make[1]: stopped in /usr/ports/www/uwsgi/work/uwsgi-2.0.5.1
1 error

make[1]: stopped in /usr/ports/www/uwsgi/work/uwsgi-2.0.5.1
</pre>

I tried uwsgi-2.0.4 but result if the same. UWSGI builds fine with php plugin only with 2.0.3 and older versions. 
I use php-5.5.13.

Thanks.

**Comment by thomaslegg** [comment]
FreeBSD ports for PHP --disable-all and then build individual plugins as shared. I modified lang/php56/Makefile to --enable-session and I've moved past the "undefined reference to `php_session_create_id'" and the uwsgi php plugin loads, but now I face an error based on not finding the function call for another shared plugin.

**Comment by iron-udjin** [comment]
Hi Tomas,

I've played around this problem a lot of time and it seems I have workaround. Uwsgi doesn't build because PHP in FreeBSD doesn't have by default built in session extension. In any other Linux distro PHP built with --enable-session configure options. I wrote small patch which allow build uwsgi-php plugin with default php build options (without modifying Makefile of php).

Put in */usr/ports/www/uwsgi/files* file *patch-plugins-php-uwsgiconfig.py*:

```
--- plugins/php/uwsgiplugin.py.orig	2015-03-18 13:42:49.352686052 +0200
+++ plugins/php/uwsgiplugin.py	2015-03-18 13:47:15.921663375 +0200
@@ -21,8 +21,9 @@
 
 LIBS = [os.popen(PHPPATH + ' --libs').read().rstrip(), '-lphp5']
 
-phplibdir = os.environ.get('UWSGICONFIG_PHPLIBDIR')
+phplibdir = os.popen(PHPPATH + ' --extension-dir').read().rstrip()
 if phplibdir:
     LIBS.append('-Wl,-rpath=%s' % phplibdir)
+    LIBS.append(' %s/session.so ' % phplibdir)
 
 GCC_LIST = ['php_plugin', 'session']
```

This patch add session extension to link options. After that linker see required symbols.

I'm not a programmer, probably there is more correct/proper way how to fix this problem.

**Comment by thomaslegg** [comment]
Looks like a great patch and things build. When I go back to run my php app
though it fails over.

*Fatal error*: Call to undefined function session_id() in

**Comment by iron-udjin** [comment]
Tomas, show please:
ldd /usr/local/bin/php
php -m

**Comment by thomaslegg** [comment]
$ ldd /usr/local/bin/php
/usr/local/bin/php:
        libelf.so.1 => /usr/lib/libelf.so.1 (0x800b15000)
        libcrypt.so.5 => /lib/libcrypt.so.5 (0x800d2a000)
        libpcre.so.1 => /usr/local/lib/libpcre.so.1 (0x800f4a000)
        libm.so.5 => /lib/libm.so.5 (0x8011bd000)
        libxml2.so.2 => /usr/local/lib/libxml2.so.2 (0x8013e5000)
        libz.so.6 => /lib/libz.so.6 (0x801777000)
        libthr.so.3 => /lib/libthr.so.3 (0x80198d000)
        libc.so.7 => /lib/libc.so.7 (0x801bb2000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x801f60000)

$ php -m
[PHP Modules]
bz2
Core
date
ereg
gd
iconv
libxml
mbstring
mysqlnd
openssl
pcre
pgsql
Reflection
session
SPL
standard
xml
zlib

**Comment by iron-udjin** [comment]
ldd /usr/local/bin/uwsgi
?

**Comment by thomaslegg** [comment]
using a modular build
/usr/local/bin/uwsgi:
        libthr.so.3 => /lib/libthr.so.3 (0x8008dc000)
        libm.so.5 => /lib/libm.so.5 (0x800b01000)
        libz.so.6 => /lib/libz.so.6 (0x800d29000)
        libkvm.so.6 => /lib/libkvm.so.6 (0x800f3f000)
        libpcre.so.1 => /usr/local/lib/libpcre.so.1 (0x801148000)
        libjail.so.1 => /lib/libjail.so.1 (0x8013bb000)
        libssl.so.8 => /usr/local/lib/libssl.so.8 (0x8015c0000)
        libcrypto.so.8 => /usr/local/lib/libcrypto.so.8 (0x80182c000)
        libc.so.7 => /lib/libc.so.7 (0x801c87000)
$ ldd /usr/local/lib/uwsgi/php_plugin.so (after using previous patch you
provided)
/usr/local/lib/uwsgi/php_plugin.so:
        libelf.so.1 => /usr/lib/libelf.so.1 (0x801607000)
        libcrypt.so.5 => /lib/libcrypt.so.5 (0x80181c000)
        libpcre.so.1 => /usr/local/lib/libpcre.so.1 (0x801a3c000)
        libm.so.5 => /lib/libm.so.5 (0x801caf000)
        libxml2.so.2 => /usr/local/lib/libxml2.so.2 (0x801ed7000)
        libz.so.6 => /lib/libz.so.6 (0x802269000)
        libphp5.so => /usr/local/lib/libphp5.so (0x80247f000)
        session.so (0x802aa9000)
        libthr.so.3 => /lib/libthr.so.3 (0x802cbc000)
        libc.so.7 => /lib/libc.so.7 (0x800822000)
        liblzma.so.5 => /usr/lib/liblzma.so.5 (0x802ee1000)

**Comment by iron-udjin** [comment]
Ah.... you're use php as a seperate plugin. I didn't test my workaround with it. For me it works fine with php as an embedded plugin.

**Comment by manasb** [comment]
@iron-udjin Thanks for the patch. I had to build uwsgi on FreeBSD 10.1 today with python and php support. Your patch works great for using php as an embedded plugin.
