### ISSUE TITLE
Build failed on OS X 10.11: SOL_SOCKET not defined

### ISSUE THREAD

**Issue by apjanke** [unbit/uwsgi#1056]
UWSGI is failing to build on OS X 10.11 with Xcode 7.0.1 for me. Built from uwsgi-2.0.11.1.tar.gz.

```
bash-3.2$ python uwsgiconfig.py --build --verbose
...
[thread 3] clang -c -O2 -I. -Wall -Werror -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -fno-strict-aliasing -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wno-format -Wno-format-security -DUWSGI_HAS_IFADDRS -DUWSGI_ZLIB -mmacosx-version-min=10.5 -DUWSGI_LOCK_USE_OSX_SPINLOCK -DUWSGI_EVENT_USE_KQUEUE -DUWSGI_EVENT_TIMER_USE_KQUEUE -DUWSGI_EVENT_FILEMONITOR_USE_KQUEUE -I/usr/local/Cellar/pcre/8.37/include -DUWSGI_PCRE -DUWSGI_ROUTING -DUWSGI_UUID -DUWSGI_VERSION="\"2.0.11.1\"" -DUWSGI_VERSION_BASE="2" -DUWSGI_VERSION_MAJOR="0" -DUWSGI_VERSION_MINOR="11" -DUWSGI_VERSION_REVISION="1" -DUWSGI_VERSION_CUSTOM="\"\"" -DUWSGI_YAML -DUWSGI_JSON -DUWSGI_SSL -I/Applications/Xcode-7.0.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/libxml2 -DUWSGI_XML -DUWSGI_XML_LIBXML2 -DUWSGI_PLUGIN_DIR="\".\"" -DUWSGI_DECLARE_EMBEDDED_PLUGINS="UDEP(python);UDEP(gevent);[...snip...] -DUWSGI_BUILD_DATE="\"02 October 2015 18:31:50\"" -o core/socket.o core/socket.c
...
core/socket.c:713:28: error: use of undeclared identifier 'SOL_TCP'
                if (setsockopt(serverfd, SOL_TCP, TCP_FASTOPEN, (const void *) &uw...
```

Here's my build log: https://gist.github.com/apjanke/33f2c1d1552ce6c74aba

Looks sort of like #966. But OS X's `<sys/socket.h>` does define SOL_SOCKET, as far as I can tell. (And from looking at the file, it's not buried in a weird `#ifdef`.) Don't know why it's not picking it up.

```
bash-3.2$ grep SOL_SOCKET /usr/include/sys/socket.h
#define	SOL_SOCKET	0xffff		/* options for socket level */
```

Found this while testing the Homebrew uwsgi formula for 10.11 (homebrew/homebrew#44018), but same error happens if I just download and build UWSGI outside of Homebrew.

**Comment by xrmx** [comment]
This should be just matter of cherry picking b608eb1772641d525bfde268fe9d6d8d0d5efde7

**Comment by apjanke** [comment]
You're right: I did that and it built fine. This is just a dup of #966. How in the world did I misread that as needing `SOL_SOCKET` and not `SOL_TCP`?

Do you know if there's an upcoming release soon?

**Comment by xrmx** [comment]
@unbit cherry-picked the fix in uwsgi-2.0 so it's just matter of cutting a new release

**Comment by pnovotnak** [comment]
Thanks for getting a fix done so soon! :+1: 

Eagerly awaiting a new release :)

**Comment by dcramer** [comment]
Just putting our hat into the ring for getting a new release out. We recommend uwsgi for all Sentry installs, and while this generally doesnt affect things, its making development a pita atm.

**Comment by unbit** [comment]
2.0.11.2 has just been released

**Comment by dcramer** [comment]
@unbit thanks as always!

**Comment by apjanke** [comment]
Works for me now. Thanks!

**Comment by thinkerou** [comment]
I use `2.0.13`, it also error, https://github.com/dropbox/changes/issues/35

**Comment by xrmx** [comment]
@thinkerou except you are not, changes depends on uwsgi==2.0.10

**Comment by thinkerou** [comment]
OK, thanks @xrmx
