### ISSUE TITLE
UWSGI 2.0.28 fails to build for Python3.12 and GCC-15

### ISSUE THREAD

**Issue by roworu** [unbit/uwsgi#2721]
Hey. After updating Fedora from 41 to 42 uwsgi now fails to build, I suspect that updating to GCC 15 is the reason here:
```
 × Failed to build `uwsgi==2.0.28`
  ├─▶ The build backend returned an error
  ╰─▶ Call to `setuptools.build_meta:__legacy__.build_wheel` failed (exit status: 1)

      [stdout]
      running bdist_wheel
      running build
      running build_py
      copying uwsgidecorators.py -> build/lib
      installing to build/bdist.linux-x86_64/wheel
      running install

      [stderr]
      /home/roworu/.cache/uv/builds-v0/.tmp272Okt/lib/python3.12/site-packages/setuptools/_distutils/dist.py:289: UserWarning: Unknown distribution option:
      'descriptions'
        warnings.warn(msg)
      /home/roworu/.cache/uv/builds-v0/.tmp272Okt/lib/python3.12/site-packages/setuptools/dist.py:759: SetuptoolsDeprecationWarning: License classifiers are
      deprecated.
      !!

              ********************************************************************************
              Please consider removing the following classifiers in favor of a SPDX license expression:

              License :: OSI Approved :: GNU General Public License v2 or later (GPLv2+)

              See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
              ********************************************************************************

      !!
        self._finalize_license_expression()
      core/master_utils.c: In function ‘uwsgi_respawn_worker’:
      core/master_utils.c:711:34: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
        711 |                 signal(SIGWINCH, worker_wakeup);
            |                                  ^~~~~~~~~~~~~
            |                                  |
            |                                  void (*)(void)
      In file included from ./uwsgi.h:168,
                       from core/master_utils.c:1:
      /usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
         88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
            |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
      core/master_utils.c:5:6: note: ‘worker_wakeup’ declared here
          5 | void worker_wakeup() {
            |      ^~~~~~~~~~~~~
      /usr/include/signal.h:72:16: note: ‘__sighandler_t’ declared here
         72 | typedef void (*__sighandler_t) (int);
            |                ^~~~~~~~~~~~~~
      core/master_utils.c:712:33: error: passing argument 2 of ‘signal’ from incompatible pointer type [-Wincompatible-pointer-types]
        712 |                 signal(SIGTSTP, worker_wakeup);
            |                                 ^~~~~~~~~~~~~
            |                                 |
            |                                 void (*)(void)
      /usr/include/signal.h:88:57: note: expected ‘__sighandler_t’ {aka ‘void (*)(int)’} but argument is of type ‘void (*)(void)’
         88 | extern __sighandler_t signal (int __sig, __sighandler_t __handler)
            |                                          ~~~~~~~~~~~~~~~^~~~~~~~~
      core/master_utils.c:5:6: note: ‘worker_wakeup’ declared here
          5 | void worker_wakeup() {
            |      ^~~~~~~~~~~~~
      /usr/include/signal.h:72:16: note: ‘__sighandler_t’ declared here
         72 | typedef void (*__sighandler_t) (int);
            |                ^~~~~~~~~~~~~~
      core/emperor.c: In function ‘emperor_loop’:
      core/emperor.c:1685:36: error: passing argument 2 of ‘uwsgi_unix_signal’ from incompatible pointer type [-Wincompatible-pointer-types]
       1685 |         uwsgi_unix_signal(SIGUSR1, emperor_stats);
            |                                    ^~~~~~~~~~~~~
            |                                    |
            |                                    void (*)(void)
      In file included from core/emperor.c:6:
      ./uwsgi.h:3483:29: note: expected ‘void (*)(int)’ but argument is of type ‘void (*)(void)’
       3483 | void uwsgi_unix_signal(int, void (*)(int));
            |                             ^~~~~~~~~~~~~
      core/emperor.c:601:13: note: ‘emperor_stats’ declared here
        601 | static void emperor_stats() {
            |             ^~~~~~~~~~~~~

      hint: This usually indicates a problem with the package or the build environment.
(.venv) /project > gcc --version                                        
gcc (GCC) 15.0.1 20250329 (Red Hat 15.0.1-0)
Copyright (C) 2025 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

(.venv) /project > python --version 
Python 3.12.10

```

**Comment by roworu** [comment]
May be bypassed by:
```bash
sudo dnf install gcc-14
```

And
```bash
export CC=gcc-14; pip install -r requirements.lock.txt
```

**Comment by roworu** [comment]
Oh, I missed that one
Closing it as not a bug then
Thanks a lot, @niol !
