### ISSUE TITLE
alarm_curl build issues

### ISSUE THREAD

**Issue by prymitive** [unbit/uwsgi#147]
`alarm_curl` plugin does not compile on ubuntu 10.04:

```
plugins/alarm_curl/alarm_curl_plugin.c:47: error: ‘CURLOPT_MAIL_RCPT’ undeclared here (not in a function)
plugins/alarm_curl/alarm_curl_plugin.c:48: error: ‘CURLOPT_MAIL_FROM’ undeclared here (not in a function)
```

This is because according to [libcurl docs](http://curl.haxx.se/libcurl/c/curl_easy_setopt.html) `CURLOPT_MAIL_RCPT` and `CURLOPT_MAIL_FROM` are available only in newer curl releases than the one from ubuntu 10.04.

We could ifdef those parts like with the diff below, but I'm not sure if this is enough or will it break anything. Can You comment on that?

```
diff --git a/plugins/alarm_curl/alarm_curl_plugin.c b/plugins/alarm_curl/alarm_curl_plugin.c
index 284de56..2e9711c 100644
--- a/plugins/alarm_curl/alarm_curl_plugin.c
+++ b/plugins/alarm_curl/alarm_curl_plugin.c
@@ -17,6 +17,7 @@ struct uwsgi_alarm_curl_opt {
 };


+#ifdef CURLOPT_MAIL_RCPT
 static void uwsgi_alarm_curl_to(CURL *curl, CURLoption option, char *arg, struct uwsgi_alarm_curl_config *uacc) {
        uacc->to = arg;
        struct curl_slist *list = NULL;
@@ -29,6 +30,7 @@ static void uwsgi_alarm_curl_to(CURL *curl, CURLoption option, char *arg, struct
        }
        curl_easy_setopt(curl, option, list);
 }
+#endif

 static void uwsgi_alarm_curl_ssl(CURL *curl, CURLoption option, char *arg, struct uwsgi_alarm_curl_config *uacc) {
        curl_easy_setopt(curl, option, (long)CURLUSESSL_ALL);
@@ -44,8 +46,12 @@ static void uwsgi_alarm_curl_set_subject(CURL *curl, CURLoption option, char *ar

 static struct uwsgi_alarm_curl_opt uaco[] = {
        {"url", CURLOPT_URL, NULL},
+#ifdef CURLOPT_MAIL_RCPT
        {"mail_to", CURLOPT_MAIL_RCPT, uwsgi_alarm_curl_to },
+#endif
+#ifdef CURLOPT_MAIL_FROM
        {"mail_from", CURLOPT_MAIL_FROM, NULL},
+#endif
        {"subject", 0, uwsgi_alarm_curl_set_subject},
        {"ssl", CURLOPT_USE_SSL, uwsgi_alarm_curl_ssl},
        {"auth_user", CURLOPT_USERNAME, NULL},
```
