### ISSUE TITLE
router_basicauth fails to build on kfreebsd

### ISSUE THREAD

**Issue by jonassmedegaard** [unbit/uwsgi#1419]
router_basicauth fails to build on kfreebsd:

plugins/router_basicauth/router_basicauth.c: In function 'router_basicauth_init_lock':
plugins/router_basicauth/router_basicauth.c:162:22: error: 'ur_basicauth_crypt_mutex' undeclared (first use in this function)
  pthread_mutex_init(&ur_basicauth_crypt_mutex, NULL);
                      ^~~~~~~~~~~~~~~~~~~~~~~~

https://buildd.debian.org/status/fetch.php?pkg=uwsgi&arch=kfreebsd-i386&ver=2.0.14%2B20161117-2&stamp=1481064044&file=log

It seems caused by commit 7f72367
