### ISSUE TITLE
Commit cecfe60b1a8b099cea76e05082adbd933341bf14 breaks Solaris build

### ISSUE THREAD

**Issue by sjthomason** [unbit/uwsgi#1933]
Solaris defines `sun` to 1 which results in a compilation error:
`./uwsgi.h:1646:22: error: expected identifier or ‘(’ before numeric constant
   struct sockaddr_un sun;
`
The offending change is below:
```diff --git a/uwsgi.h b/uwsgi.h
index 37b1e0f4..2df7e5c4 100755
--- a/uwsgi.h
+++ b/uwsgi.h
@@ -1375,8 +1375,11 @@ struct wsgi_request {
        char *appid;
        uint16_t appid_len;
 
-       //this is big enough to contain sockaddr_in
-       struct sockaddr_un c_addr;
+       union address {
+               struct sockaddr_in sin;
+               struct sockaddr_in6 sin6;
+               struct sockaddr_un sun;
+       } c_addr;```

**Comment by nwilkens** [comment]
Reading http://postfix.1071664.n5.nabble.com/Postfix-3-4-4-compile-problems-on-Solaris-11-td100796.html#a100835 helped me solve this.

`#undef sun` to avoid conflicts with the "sun" macro; or sun should be renamed to s_un.
